spring:
  application:
    name: local-grpc-server
  profiles:
    active: @spring.profiles.active@
  datasource:
    driver-class-name: ${db.driver}
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
  jpa:
    hibernate:
#      ddl-auto: update
      ddl-auto: create-drop
    show-sql: true
  redis:
    database: 0
    host: 192.168.16.101
    port: 6379

grpc:
  server:
    port: 9898

#db:
#  url: jdbc:mysql://192.168.16.101:3306/vito_bank?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
#  username: root
#  password: 12345678
#  driver: com.mysql.cj.jdbc.Driver

#vito:
#  # 审计日志默认是false,log-type默认为logger
#  audit-log:
#    enabled: true
#    log-type: db